/* khz_xlsx_test.c - end-to-end test: a deflated .xlsx becomes exact cells.
 *
 * What this covers that khz_sheet_selftest does not:
 *
 *   - the zip central directory parser, on an archive written by a third
 *     party rather than by khz_xlsx.c
 *   - the DEFLATE decoder, against streams produced by zlib
 *   - CRC-32 verification of inflated output, which is the check that would
 *     catch a decoder that produced plausible but wrong bytes
 *   - the worksheet XML parser
 *   - cell commits through khz_sheet_set_*, and therefore the SHA-256 proof
 *     chain and the commit log
 *   - khz_sheet_sum on 200 same-denominator values, which is the SIMD path
 *   - exact rational division: the average of these cells is not an integer
 *
 * The fixture is generated by tests/make_fixture.py, which CMake runs at build
 * time. Its DEFLATE streams and CRC-32 values come from zlib, so a passing run
 * means an implementation this project did not write agrees with the bytes
 * this decoder produced. That independence is the entire point; a fixture this
 * project compressed itself would only prove the code agrees with itself.
 *
 * stdio and malloc appear below. That is deliberate and confined to this file:
 * a test harness has to get a file into memory somehow, and
 * khz_xlsx_reader_load takes bytes the caller already holds. Nothing inside
 * the library allocates from the heap.
 */

#include <stdio.h>
#include <stdlib.h>

#include "khz_arena.h"
#include "khz_sheet.h"
#include "khz_simd.h"
#include "khz_xlsx_reader.h"

/* Must match tests/make_fixture.py. If they disagree the test fails loudly on
 * the cell count rather than checking the wrong coordinates. */
#define KHZ_TEST_ROWS ((uint32_t)25)
#define KHZ_TEST_COLS ((uint32_t)8)

/* The fixture's rule: xlsx row r (1-based), column c (0-based) holds 10*r + c.
 * The grid is 0-based, so that cell is (c, r-1). */
static int64_t expected_value(uint32_t col, uint32_t row)
{
    return (int64_t)10 * ((int64_t)row + 1) + (int64_t)col;
}

static int failures;

static void fail(const char *what, const char *detail)
{
    printf("FAIL %s: %s\n", what, detail ? detail : "");
    failures++;
}

static unsigned char *read_whole_file(const char *path, size_t *out_size)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        return NULL;
    }
    if (fseek(f, 0, SEEK_END) != 0) {
        fclose(f);
        return NULL;
    }
    long end = ftell(f);
    if (end < 0 || fseek(f, 0, SEEK_SET) != 0) {
        fclose(f);
        return NULL;
    }
    size_t size = (size_t)end;
    unsigned char *bytes = (unsigned char *)malloc(size ? size : 1);
    if (!bytes) {
        fclose(f);
        return NULL;
    }
    if (fread(bytes, 1, size, f) != size) {
        free(bytes);
        fclose(f);
        return NULL;
    }
    fclose(f);
    *out_size = size;
    return bytes;
}

/* Reads one cell by summing a 1x1 range. That uses only the public API and
 * avoids reaching into KhzCell, so this test does not have to be updated when
 * the cell layout changes. */
static void check_cell(KhzSheet *sheet, uint32_t col, uint32_t row)
{
    KhzRational value;
    size_t counted = 0;
    KhzSheetStatus st = khz_sheet_sum(sheet, col, row, col, row, &value, &counted);

    if (st != KHZ_SHEET_OK) {
        char buf[96];
        snprintf(buf, sizeof buf, "cell (%u,%u) returned %s",
                 (unsigned)col, (unsigned)row, khz_sheet_status_name(st));
        fail("cell", buf);
        return;
    }
    if (counted != 1) {
        char buf[96];
        snprintf(buf, sizeof buf, "cell (%u,%u) counted %zu, expected 1",
                 (unsigned)col, (unsigned)row, counted);
        fail("cell", buf);
        return;
    }

    int64_t want = expected_value(col, row);
    /* den must be 1: these are integers, and a denominator of anything else
     * would mean the parser produced a value it should not have. */
    if (value.den != 1 || value.num != want) {
        char buf[128];
        snprintf(buf, sizeof buf, "cell (%u,%u) is %lld/%lld, expected %lld/1",
                 (unsigned)col, (unsigned)row,
                 (long long)value.num, (long long)value.den, (long long)want);
        fail("cell", buf);
    }
}

int main(int argc, char **argv)
{
    if (argc != 2) {
        fprintf(stderr, "usage: khz_xlsx_test <fixture.xlsx>\n");
        return 2;
    }

    size_t size = 0;
    unsigned char *bytes = read_whole_file(argv[1], &size);
    if (!bytes) {
        fprintf(stderr, "cannot read fixture: %s\n", argv[1]);
        return 2;
    }
    printf("fixture     = %s (%zu bytes)\n", argv[1], size);

    KhzSheet sheet;
    KhzSheetStatus st = khz_sheet_init_default(&sheet);
    if (st != KHZ_SHEET_OK) {
        fprintf(stderr, "sheet init: %s\n", khz_sheet_status_name(st));
        free(bytes);
        return 2;
    }

    KhzXlsxReader reader;
    st = khz_xlsx_reader_init(&reader, khz_sheet_arena(&sheet));
    if (st != KHZ_SHEET_OK) {
        fail("reader init", khz_sheet_status_name(st));
        khz_sheet_destroy(&sheet);
        free(bytes);
        return 1;
    }

    st = khz_xlsx_reader_read(&reader, &sheet, bytes, size);
    printf("read        = %s\n", khz_sheet_status_name(st));
    if (st != KHZ_SHEET_OK) {
        fail("read", khz_sheet_status_name(st));
        khz_sheet_destroy(&sheet);
        free(bytes);
        return 1;
    }

    /* Every part must have been deflated. If the fixture generator ever
     * produces a STORED part the reader would take its stored path and this
     * test would pass without the decoder running at all - a test that
     * silently stops testing is worse than no test. */
    size_t entries = khz_xlsx_reader_entry_count(&reader);
    printf("entries     = %zu\n", entries);
    if (entries == 0) {
        fail("entries", "archive parsed to zero entries");
    }
    for (size_t i = 0; i < entries; i++) {
        const KhzXlsxEntry *e = &reader.entries[i];
        if (e->method != KHZ_XLSX_METHOD_DEFLATE) {
            char buf[128];
            snprintf(buf, sizeof buf,
                     "part %s is method %u; fixture did not exercise DEFLATE",
                     e->name ? e->name : "(unnamed)", (unsigned)e->method);
            fail("method", buf);
        }
        if (e->declared_crc32 != e->actual_crc32) {
            char buf[160];
            snprintf(buf, sizeof buf, "part %s crc %08x declared, %08x computed",
                     e->name ? e->name : "(unnamed)",
                     e->declared_crc32, e->actual_crc32);
            fail("crc", buf);
        }
    }

    KhzXlsxReadReport rep;
    if (khz_xlsx_reader_report(&reader, &rep) == KHZ_SHEET_OK) {
        printf("report      = entries=%llu cells_seen=%llu loaded=%llu "
               "unsupported=%llu crc_failures=%llu\n",
               (unsigned long long)rep.entries_seen,
               (unsigned long long)rep.cells_seen,
               (unsigned long long)rep.cells_loaded,
               (unsigned long long)rep.cells_unsupported,
               (unsigned long long)rep.crc_failures);
        if (rep.crc_failures != 0) {
            fail("report", "crc_failures is not zero");
        }
        if (rep.cells_unsupported != 0) {
            fail("report", "a cell in the fixture was not modelled");
        }
    }

    size_t expect_cells = (size_t)KHZ_TEST_ROWS * (size_t)KHZ_TEST_COLS;
    size_t got_cells = khz_sheet_cell_count(&sheet);
    printf("cells       = %zu (expect %zu)\n", got_cells, expect_cells);
    if (got_cells != expect_cells) {
        fail("cells", "cell count does not match the fixture");
    }

    /* Every cell, not a sample. 200 checks is cheap and a wrong value in the
     * middle of the grid is exactly the kind of thing a spot check misses. */
    int64_t expect_total = 0;
    for (uint32_t row = 0; row < KHZ_TEST_ROWS; row++) {
        for (uint32_t col = 0; col < KHZ_TEST_COLS; col++) {
            check_cell(&sheet, col, row);
            expect_total += expected_value(col, row);
        }
    }

    KhzRational total;
    size_t counted = 0;
    st = khz_sheet_sum(&sheet, 0, 0, KHZ_TEST_COLS - 1, KHZ_TEST_ROWS - 1,
                       &total, &counted);
    printf("sum         = %s %lld/%lld counted=%zu (expect %lld/1 over %zu)\n",
           khz_sheet_status_name(st), (long long)total.num,
           (long long)total.den, counted, (long long)expect_total, expect_cells);
    if (st != KHZ_SHEET_OK || total.den != 1 || total.num != expect_total ||
        counted != expect_cells) {
        fail("sum", "range sum is not the exact expected total");
    }

    /* The average is 26700/200, which reduces to 267/2. Asserting the
     * unreduced literal would assert the wrong thing, and asserting 133.5
     * would assert a rounding this project does not do. Cross-multiply
     * instead: avg.num * count == total * avg.den holds for any correct
     * representation of the same rational. */
    KhzRational avg;
    counted = 0;
    st = khz_sheet_avg(&sheet, 0, 0, KHZ_TEST_COLS - 1, KHZ_TEST_ROWS - 1,
                       &avg, &counted);
    printf("avg         = %s %lld/%lld counted=%zu\n",
           khz_sheet_status_name(st), (long long)avg.num,
           (long long)avg.den, counted);
    if (st != KHZ_SHEET_OK || avg.den == 0 || counted != expect_cells ||
        avg.num * (int64_t)expect_cells != expect_total * avg.den) {
        fail("avg", "average is not exactly total/count");
    }

    /* Loading is an edit: every cell should have been committed onto the
     * chain, and with each cell written exactly once the audit can make its
     * strongest claim - nothing superseded, nothing dropped. */
    size_t failed_index = 0;
    st = khz_sheet_verify_chain(&sheet, &failed_index);
    printf("chain       = %s failed_index=%zu commits=%llu\n",
           khz_sheet_status_name(st), failed_index,
           (unsigned long long)khz_sheet_commits(&sheet));
    if (st != KHZ_SHEET_OK) {
        fail("chain", "proof chain does not verify after load");
    }
    if (khz_sheet_commits(&sheet) != (uint64_t)expect_cells) {
        fail("chain", "commit count does not match the cells loaded");
    }

    KhzChainAudit audit;
    if (khz_sheet_audit_chain(&sheet, &audit) == KHZ_SHEET_OK) {
        printf("audit       = examined=%llu verified=%llu superseded=%llu "
               "dropped=%llu\n",
               (unsigned long long)audit.entries_examined,
               (unsigned long long)audit.cells_verified,
               (unsigned long long)audit.superseded,
               (unsigned long long)audit.dropped);
        if (audit.cells_verified != (uint64_t)expect_cells ||
            audit.superseded != 0 || audit.dropped != 0) {
            fail("audit", "audit could not verify every loaded cell");
        }
    }

    char hex[KHZ_SHA256_HEX_BYTES];
    if (khz_sheet_proof_hex(&sheet, hex) == KHZ_SHEET_OK) {
        printf("proof       = %s\n", hex);
    }

    /* No heap fallback anywhere in the library: a rejection would mean the
     * arena was exhausted and something returned an error rather than
     * allocating, and this fixture is far too small for that to be legitimate. */
    KhzArena *arena = khz_sheet_arena(&sheet);
    printf("arena       = used=%zu peak=%zu rejections=%llu kernel=%s lanes=%zu\n",
           khz_arena_used(arena), khz_arena_peak(arena),
           (unsigned long long)khz_arena_rejections(arena),
           khz_simd_kernel_name(khz_simd_kernel()), khz_simd_lanes());
    if (khz_arena_rejections(arena) != 0) {
        fail("arena", "the arena rejected an allocation");
    }

    khz_xlsx_reader_reset(&reader);
    khz_sheet_destroy(&sheet);
    free(bytes);

    printf("%s failures=%d\n", failures == 0 ? "ALL PASS" : "FAILURES", failures);
    return failures == 0 ? 0 : 1;
}
